import { CastType } from '../entity'
import { getOrCreate } from './metadata'

export interface ColumnOptions {
  /** Automatic type coercion when reading from the database. */
  cast?: CastType
  /** Mark this column as the primary key. */
  primaryKey?: boolean
  /** Column value is generated by the database (e.g. AUTOINCREMENT). Excluded from INSERT/UPDATE. */
  autoGenerated?: boolean
}

/** Map a class property to a database column. */
export function Column(options?: ColumnOptions): PropertyDecorator {
  return (target, propertyKey) => {
    const m = getOrCreate(target as object)

    m.columns.push({ name: String(propertyKey), ...options })
  }
}
