import { DataSource } from '../../database/DataSource'
import { CastType } from '../CastType'
import { Relationship } from '../Relationship'
import { registry } from './metadata'

export interface EntityOptions {
  /** Database table name. Defaults to lowercase class name + 's'. */
  table?: string
  /** Primary key column name. Defaults to 'id'. */
  primaryKey?: string
  /** DataSource to use. Defaults to DB.getActiveSource(). */
  source?: DataSource | null
}

/**
 * Marks a class as an Active Record entity.
 * The class must extend BaseEntity; this decorator reads the metadata
 * accumulated by the property decorators (@Column, @HasMany, …) and assigns
 * it to the static fields BaseEntity expects (table, primaryKey, fields, …).
 */
export function Entity(options?: EntityOptions) {
  return function <T extends { new (...args: any[]): {} }>(EntityClass: T): T {
    // Read metadata accumulated by property decorators on the class prototype.
    const meta = registry.get(EntityClass.prototype) ?? { columns: [], relationships: [] }
    const tableName = options?.table ?? EntityClass.name.toLowerCase() + 's'
    const primaryKeyMeta = meta.columns.find((c) => c.primaryKey)
    const primaryKeyCol =
      (primaryKeyMeta && (primaryKeyMeta.columnName ?? primaryKeyMeta.name)) ?? options?.primaryKey ?? 'id'
    const fieldNames = meta.columns.map((c) => c.name)
    // Property name → database column name (defaults to the property name)
    const columnsMap: Record<string, string> = {}

    meta.columns.forEach((c) => {
      columnsMap[c.name] = c.columnName ?? c.name
    })
    const autoGeneratedFields = meta.columns.filter((c) => c.autoGenerated).map((c) => c.name)
    const castsMap: Record<string, CastType> = {}

    meta.columns.forEach((c) => {
      if (c.cast) {
        castsMap[c.name] = c.cast
      }
    })
    const relsMap: Record<string, Relationship> = {}

    meta.relationships.forEach((r) => {
      relsMap[r.name] = r.relationship
    })

    // Assign the static metadata consumed by BaseEntity / EntityQuery.
    const cls = EntityClass as any

    cls.table = tableName
    cls.primaryKey = primaryKeyCol
    cls.fields = fieldNames
    cls.columnsMap = columnsMap
    cls.autoGeneratedFields = autoGeneratedFields
    cls.casts = castsMap
    cls.relationships = relsMap
    cls.source = options?.source ?? null

    return EntityClass
  }
}
