import { DataSource } from '../../data-source'
import { DB } from '../../db'
import { Field } from '../../query'
import { Condition, ConditionGroup } from '../../query/conditions'
import { OrderByDirection } from '../../query/features/has-order-by-fields'
import { CastType } from '../entity'
import { EntityQuery } from '../entity-query'
import { Relationship } from '../relationship'
import { applyCast } from './casts'
import { registry } from './metadata'

export interface EntityOptions {
  /** Database table name. Defaults to lowercase class name + 's'. */
  table?: string
  /** Primary key column name. Defaults to 'id'. */
  primaryKey?: string
  /** DataSource to use. Defaults to DB.getActiveSource(). */
  source?: DataSource | null
}

/**
 * Marks a class as an Active Record entity.
 * Injects static query methods (find, where, get, with, …) — no base class required.
 * Use saveEntity() and deleteEntity() for persistence.
 */
export function Entity(options?: EntityOptions) {
  return function <T extends { new (...args: any[]): {} }>(BaseClass: T) {
    // Read metadata accumulated by property decorators on BaseClass.prototype.
    const originalName = BaseClass.name
    const meta = registry.get(BaseClass.prototype) ?? { columns: [], relationships: [] }
    const tableName = options?.table ?? originalName.toLowerCase() + 's'
    const primaryKeyCol = meta.columns.find((c) => c.primaryKey)?.name ?? options?.primaryKey ?? 'id'
    const fieldNames = meta.columns.map((c) => c.name)
    const autoGeneratedFields = meta.columns.filter((c) => c.autoGenerated).map((c) => c.name)
    const castsMap: Record<string, CastType> = {}

    meta.columns.forEach((c) => {
      if (c.cast) {
        castsMap[c.name] = c.cast
      }
    })
    const relsMap: Record<string, Relationship> = {}

    meta.relationships.forEach((r) => {
      relsMap[r.name] = r.relationship
    })
    const configuredSource = options?.source ?? null

    // ── Closures shared by static methods ────────────────────────────────

    function resolveSource(): DataSource {
      return configuredSource ?? DB.getActiveSource()
    }

    function hydrateRow(row: Record<string, any>): any {
      const instance = new Enhanced() as any
      const cols = fieldNames.length > 0 ? fieldNames : Object.keys(row)

      for (const col of cols) {
        if (!(col in row)) {
          continue
        }

        const cast = castsMap[col]

        instance[col] = cast ? applyCast(row[col], cast) : row[col]
      }

      return instance
    }

    function buildQuery(): EntityQuery<any> {
      return new EntityQuery<any>(Enhanced as any, resolveSource().table(tableName))
    }

    // ── Enhanced class — wraps BaseClass and injects all methods ──────────

    class Enhanced extends BaseClass {
      // Static metadata (also used by EntityQuery internals)
      static readonly table = tableName
      static readonly primaryKey = primaryKeyCol
      static readonly fields = fieldNames
      static readonly autoGeneratedFields = autoGeneratedFields
      static readonly casts = castsMap
      static readonly relationships = relsMap
      static readonly source = configuredSource

      static fromRow(row: Record<string, any>): any {
        return hydrateRow(row)
      }

      toJSON(): Record<string, any> {
        const result: Record<string, any> = {}

        // Own enumerable properties — column values set by hydrateRow
        for (const key of Object.keys(this as any)) {
          result[key] = (this as any)[key]
        }

        // Getters defined on the user's class prototype (computed attributes)
        for (const key of Object.getOwnPropertyNames(BaseClass.prototype)) {
          if (key === 'constructor' || key in result) {
            continue
          }

          const descriptor = Object.getOwnPropertyDescriptor(BaseClass.prototype, key)

          if (descriptor && typeof descriptor.get === 'function') {
            try {
              result[key] = (this as any)[key]
            } catch {
              // skip getters that throw (e.g. unloaded relationships)
            }
          }
        }

        return result
      }

      // ── Static query methods ───────────────────────────────────────────

      static async find(id: any): Promise<any> {
        return buildQuery().find(id)
      }

      static async get(): Promise<any[]> {
        return buildQuery().get()
      }

      static async first(): Promise<any> {
        return buildQuery().first()
      }

      static where(callback: (group: ConditionGroup) => void): EntityQuery<any>
      static where(condition: Condition): EntityQuery<any>
      static where(field: Field, value: any): EntityQuery<any>
      static where(field: Field, operator: string, value: any): EntityQuery<any>
      static where(...args: any[]): EntityQuery<any> {
        return (buildQuery() as any).where(...args)
      }

      static whereIn(field: Field, values: any[]): EntityQuery<any> {
        return buildQuery().whereIn(field, values)
      }

      static whereNotIn(field: Field, values: any[]): EntityQuery<any> {
        return buildQuery().whereNotIn(field, values)
      }

      static whereBetween(field: Field, range: [any, any]): EntityQuery<any> {
        return buildQuery().whereBetween(field, range)
      }

      static whereNotBetween(field: Field, range: [any, any]): EntityQuery<any> {
        return buildQuery().whereNotBetween(field, range)
      }

      static whereNull(field: Field): EntityQuery<any> {
        return buildQuery().whereNull(field)
      }

      static whereNotNull(field: Field): EntityQuery<any> {
        return buildQuery().whereNotNull(field)
      }

      static whereLike(field: Field, pattern: string): EntityQuery<any> {
        return buildQuery().whereLike(field, pattern)
      }

      static whereNotLike(field: Field, pattern: string): EntityQuery<any> {
        return buildQuery().whereNotLike(field, pattern)
      }

      static whereColumn(field: Field, column: Field): EntityQuery<any>
      static whereColumn(field: Field, operator: string, column: Field): EntityQuery<any>
      static whereColumn(...args: any[]): EntityQuery<any> {
        return (buildQuery() as any).whereColumn(...args)
      }

      static orderBy(field: Field, direction?: OrderByDirection): EntityQuery<any> {
        return buildQuery().orderBy(field, direction)
      }

      static limit(value: number): EntityQuery<any> {
        return buildQuery().limit(value)
      }

      static offset(value: number): EntityQuery<any> {
        return buildQuery().offset(value)
      }

      static select(...args: (Field | Field[])[]): EntityQuery<any> {
        return (buildQuery() as any).select(...args)
      }

      static with(relations: string | string[], ...rest: string[]): EntityQuery<any> {
        return buildQuery().with(relations, ...rest)
      }

      static joinRelationship(name: string): EntityQuery<any> {
        return buildQuery().joinRelationship(name)
      }

      static innerJoinRelationship(name: string): EntityQuery<any> {
        return buildQuery().innerJoinRelationship(name)
      }

      static leftJoinRelationship(name: string): EntityQuery<any> {
        return buildQuery().leftJoinRelationship(name)
      }
    }

    // Preserve the original class name so default table names and stack traces stay clean.
    Object.defineProperty(Enhanced, 'name', { value: originalName })

    return Enhanced as unknown as T
  }
}
