import { DataSet } from '../database/DataSet'
import { DataSource } from '../database/DataSource'
import { DB } from '../database/DB'
import { Field, InsertQuery } from '../query'
import { Condition, ConditionGroup } from '../query/conditions'
import { OrderByDirection } from '../query/features/HasOrderByFields'
import { CastType } from './CastType'
import { applyCast, applyCastForStorage } from './decorators/casts'
import { EntityQuery } from './EntityQuery'
import { Relationship } from './Relationship'

/** A concrete entity class: constructible and carrying the BaseEntity statics. */
export type EntityClass<T extends BaseEntity = BaseEntity> = typeof BaseEntity & (new () => T)

/**
 * Abstract Active Record base class. Entities extend BaseEntity and are
 * decorated with @Entity/@Column — the decorators fill in the static metadata,
 * and BaseEntity provides every static query method (find, where, with, …)
 * plus the save() and delete() instance methods.
 */
export abstract class BaseEntity {
  // ── Static metadata (populated by the @Entity decorator) ─────────────────────

  /** Database table name. */
  static table: string
  /** Primary key column name. */
  static primaryKey: string
  /** Entity property names registered with @Column. */
  static fields: string[]
  /** Property name → database column name. */
  static columnsMap: Record<string, string>
  /** Properties whose values are generated by the database. */
  static autoGeneratedFields: string[]
  /** Property name → cast type. */
  static casts: Record<string, CastType>
  /** Relationship name → relationship definition. */
  static relationships: Record<string, Relationship>
  /** Registered DataSource name. When null, the entity operates directly on DB. */
  static source: string | null

  // ── Internals ────────────────────────────────────────────────────────────────

  static getSource(): DataSource {
    return this.source ? DB.source(this.source) : DB.getActiveSource()
  }

  /** Creates a new EntityQuery for this entity. */
  static query<T extends BaseEntity>(this: EntityClass<T>): EntityQuery<T> {
    return new EntityQuery<T>(this as any, this.getSource().table(this.table))
  }

  /** Hydrates a database row into an entity instance (applying casts). */
  static fromRow<T extends BaseEntity>(this: EntityClass<T>, row: Record<string, any>): T {
    const instance = new (this as any)()
    const fieldNames = this.fields ?? []
    const columnsMap = this.columnsMap ?? {}
    const castsMap = this.casts ?? {}
    const cols = fieldNames.length > 0 ? fieldNames : Object.keys(row)

    for (const prop of cols) {
      const col = columnsMap[prop] ?? prop

      if (!(col in row)) {
        continue
      }

      const cast = castsMap[prop]

      instance[prop] = cast ? applyCast(row[col], cast) : row[col]
    }

    return instance
  }

  // ── Static query methods ─────────────────────────────────────────────────────

  static async find<T extends BaseEntity>(this: EntityClass<T>, id: any): Promise<T | null> {
    return this.query().find(id)
  }

  static async get<T extends BaseEntity>(this: EntityClass<T>): Promise<T[]> {
    return this.query().get()
  }

  static async first<T extends BaseEntity>(this: EntityClass<T>): Promise<T | null> {
    return this.query().first()
  }

  static where<T extends BaseEntity>(this: EntityClass<T>, callback: (group: ConditionGroup) => void): EntityQuery<T>
  static where<T extends BaseEntity>(this: EntityClass<T>, condition: Condition): EntityQuery<T>
  static where<T extends BaseEntity>(this: EntityClass<T>, field: Field, value: any): EntityQuery<T>
  static where<T extends BaseEntity>(this: EntityClass<T>, field: Field, operator: string, value: any): EntityQuery<T>
  static where(this: any, ...args: any[]): EntityQuery<any> {
    return this.query().where(...args)
  }

  static whereIn<T extends BaseEntity>(this: EntityClass<T>, field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereIn(field, values)
  }

  static whereNotIn<T extends BaseEntity>(this: EntityClass<T>, field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereNotIn(field, values)
  }

  static whereBetween<T extends BaseEntity>(this: EntityClass<T>, field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereBetween(field, range)
  }

  static whereNotBetween<T extends BaseEntity>(this: EntityClass<T>, field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereNotBetween(field, range)
  }

  static whereNull<T extends BaseEntity>(this: EntityClass<T>, field: Field): EntityQuery<T> {
    return this.query().whereNull(field)
  }

  static whereNotNull<T extends BaseEntity>(this: EntityClass<T>, field: Field): EntityQuery<T> {
    return this.query().whereNotNull(field)
  }

  static whereLike<T extends BaseEntity>(this: EntityClass<T>, field: Field, pattern: string): EntityQuery<T> {
    return this.query().whereLike(field, pattern)
  }

  static whereNotLike<T extends BaseEntity>(this: EntityClass<T>, field: Field, pattern: string): EntityQuery<T> {
    return this.query().whereNotLike(field, pattern)
  }

  static whereColumn<T extends BaseEntity>(this: EntityClass<T>, field: Field, column: Field): EntityQuery<T>
  static whereColumn<T extends BaseEntity>(
    this: EntityClass<T>,
    field: Field,
    operator: string,
    column: Field
  ): EntityQuery<T>
  static whereColumn(this: any, ...args: any[]): EntityQuery<any> {
    return this.query().whereColumn(...args)
  }

  static orderBy<T extends BaseEntity>(
    this: EntityClass<T>,
    field: Field,
    direction?: OrderByDirection
  ): EntityQuery<T> {
    return this.query().orderBy(field, direction)
  }

  static limit<T extends BaseEntity>(this: EntityClass<T>, value: number): EntityQuery<T> {
    return this.query().limit(value)
  }

  static offset<T extends BaseEntity>(this: EntityClass<T>, value: number): EntityQuery<T> {
    return this.query().offset(value)
  }

  static select<T extends BaseEntity>(this: EntityClass<T>, ...fields: (Field | Field[])[]): EntityQuery<T> {
    return this.query().select(...fields)
  }

  static with<T extends BaseEntity>(
    this: EntityClass<T>,
    relations: string | string[],
    ...rest: string[]
  ): EntityQuery<T> {
    return this.query().with(relations, ...rest)
  }

  static joinRelationship<T extends BaseEntity>(this: EntityClass<T>, relationName: string): EntityQuery<T> {
    return this.query().joinRelationship(relationName)
  }

  static innerJoinRelationship<T extends BaseEntity>(this: EntityClass<T>, relationName: string): EntityQuery<T> {
    return this.query().innerJoinRelationship(relationName)
  }

  static leftJoinRelationship<T extends BaseEntity>(this: EntityClass<T>, relationName: string): EntityQuery<T> {
    return this.query().leftJoinRelationship(relationName)
  }

  // ── Persistence ──────────────────────────────────────────────────────────────

  /**
   * Persists the entity to the database.
   * - If the primary key is set → UPDATE (auto-generated columns are excluded from SET).
   * - If the primary key is null/undefined → INSERT (auto-generated columns are excluded;
   *   the generated PK is written back to the instance).
   */
  async save(): Promise<void> {
    const cls = this.constructor as EntityClass
    const pk = cls.primaryKey
    const fieldNames = cls.fields ?? []
    const autoGeneratedFields = cls.autoGeneratedFields ?? []
    const castsMap = cls.casts ?? {}
    const columnsMap = cls.columnsMap ?? {}
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const source = cls.getSource()
    // Build the row, skipping auto-generated columns (DB manages their values)
    const row: DataSet = {}
    const cols =
      fieldNames.length > 0
        ? fieldNames
        : Object.keys(this as any).filter((k) => typeof (this as any)[k] !== 'function')

    for (const col of cols) {
      if (autoGeneratedFields.includes(col)) {
        continue
      }

      const value = (this as any)[col]

      if (value === undefined) {
        continue
      }

      const cast = castsMap[col]

      row[columnsMap[col] ?? col] = cast ? applyCastForStorage(value, cast) : value
    }

    if ((this as any)[pkProp] != null) {
      // UPDATE — also exclude PK from SET clause
      const updateRow = { ...row }

      delete updateRow[pk]
      await source
        .table(cls.table)
        .where(pk, (this as any)[pkProp])
        .update(updateRow)
    } else {
      // INSERT — get connection to read back the generated ID
      const conn = await source.getConnection()

      try {
        await conn.execute(new InsertQuery().setTable(cls.table).setFields(row))

        if (autoGeneratedFields.includes(pkProp)) {
          ;(this as any)[pkProp] = await conn.lastInsertId()
        }
      } finally {
        await conn.close()
      }
    }
  }

  /**
   * Deletes the entity from the database by its primary key.
   * Throws if the primary key is not set.
   */
  async delete(): Promise<void> {
    const cls = this.constructor as EntityClass
    const pk = cls.primaryKey
    const columnsMap = cls.columnsMap ?? {}
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const pkValue = (this as any)[pkProp]

    if (pkValue == null) {
      throw new Error('Cannot delete an entity without a primary key value.')
    }

    await cls.getSource().table(cls.table).where(pk, pkValue).delete()
  }

  // ── Serialization ────────────────────────────────────────────────────────────

  toJSON(): Record<string, any> {
    const result: Record<string, any> = {}

    // Own enumerable properties — column values set by fromRow
    for (const key of Object.keys(this as any)) {
      result[key] = (this as any)[key]
    }

    // Getters defined on the entity's prototype chain (computed attributes)
    let proto = Object.getPrototypeOf(this)

    while (proto && proto !== BaseEntity.prototype && proto !== Object.prototype) {
      for (const key of Object.getOwnPropertyNames(proto)) {
        if (key === 'constructor' || key in result) {
          continue
        }

        const descriptor = Object.getOwnPropertyDescriptor(proto, key)

        if (descriptor && typeof descriptor.get === 'function') {
          try {
            result[key] = (this as any)[key]
          } catch {
            // skip getters that throw (e.g. unloaded relationships)
          }
        }
      }

      proto = Object.getPrototypeOf(proto)
    }

    return result
  }
}
