import { DataSet } from '../database/DataSet'
import { DataSource } from '../database/DataSource'
import { DB } from '../database/DB'
import { Field, InsertQuery } from '../database/query'
import { Condition, ConditionGroup } from '../database/query/conditions'
import { OrderByDirection } from '../database/query/features/HasOrderByFields'
import { CastType } from './CastType'
import { applyCast, applyCastForStorage } from './decorators/casts'
import { EntityQuery } from './EntityQuery'
import { Relationship } from './Relationship'

// ── Entity metadata ───────────────────────────────────────────────────────────

export interface EntityMeta {
  table: string
  primaryKey: string
  fields: string[]
  columnsMap: Record<string, string>
  autoGeneratedFields: string[]
  casts: Record<string, CastType>
  relationships: Record<string, Relationship>
  source: string | null
}

/**
 * Internal store: entity constructor → metadata.
 * Populated exclusively by registerEntityMeta(), called from the @Entity decorator.
 * Decorators never write anything onto the entity class itself.
 */
const _metaStore = new Map<any, EntityMeta>()

/**
 * Called by the @Entity decorator to register an entity's metadata.
 * This is the only place that writes to _metaStore.
 */
export function registerEntityMeta(entityClass: any, meta: EntityMeta): void {
  _metaStore.set(entityClass, meta)
  // Invalidate any cached repository so it picks up fresh metadata
  _repoCache.delete(entityClass)
}

// ── Repository cache ──────────────────────────────────────────────────────────

const _repoCache = new Map<any, EntityRepository<any>>()

/**
 * Static facade for accessing entity repositories.
 *
 * Works with any entity class, whether or not it extends BaseEntity:
 *
 *   Repository.get(Country).where('name', 'Argentina').first()
 *   Repository.get(Country).save(countryInstance)
 *   Repository.get(Country).delete(countryInstance)
 */
export class Repository {
  static get<T>(entityClass: new (...args: any[]) => T): EntityRepository<T> {
    if (!_repoCache.has(entityClass)) {
      _repoCache.set(entityClass, new EntityRepository<T>(entityClass))
    }

    return _repoCache.get(entityClass)! as EntityRepository<T>
  }
}

// ── EntityRepository ──────────────────────────────────────────────────────────

/**
 * All query, hydration, and persistence logic for a single entity class.
 * This is the single source of truth — BaseEntity methods are thin delegates
 * to this class, and plain (non-BaseEntity) entities use it directly via
 * Repository.get(EntityClass).
 *
 * Metadata is read from the module-level _metaStore, populated by @Entity.
 * The entity class itself is never modified by any decorator.
 */
export class EntityRepository<T> {
  private readonly _entityClass: new (...args: any[]) => T

  constructor(entityClass: new (...args: any[]) => T) {
    this._entityClass = entityClass
  }

  // ── Metadata accessors ─────────────────────────────────────────────────────

  private _meta(): EntityMeta {
    const meta = _metaStore.get(this._entityClass)

    if (!meta) {
      throw new Error(`Entity "${(this._entityClass as any).name}" has not been decorated with @Entity.`)
    }

    return meta
  }

  get table(): string {
    return this._meta().table
  }

  get primaryKey(): string {
    return this._meta().primaryKey
  }

  get fields(): string[] {
    return this._meta().fields
  }

  get columnsMap(): Record<string, string> {
    return this._meta().columnsMap
  }

  get autoGeneratedFields(): string[] {
    return this._meta().autoGeneratedFields
  }

  get casts(): Record<string, CastType> {
    return this._meta().casts
  }

  get relationships(): Record<string, Relationship> {
    return this._meta().relationships
  }

  get sourceName(): string | null {
    return this._meta().source
  }

  // ── DataSource ─────────────────────────────────────────────────────────────

  getSource(): DataSource {
    return this.sourceName ? DB.source(this.sourceName) : DB.getActiveSource()
  }

  // ── Query factory ──────────────────────────────────────────────────────────

  /** Creates a fresh EntityQuery for this entity. */
  query(): EntityQuery<T> {
    return new EntityQuery<T>(this, this.getSource().table(this.table))
  }

  // ── Hydration ──────────────────────────────────────────────────────────────

  /** Hydrates a database row into a typed entity instance, applying any casts. */
  fromRow(row: Record<string, any>): T {
    const instance = new (this._entityClass as any)()
    const fieldNames = this.fields
    const columnsMap = this.columnsMap
    const castsMap = this.casts
    const cols = fieldNames.length > 0 ? fieldNames : Object.keys(row)

    for (const prop of cols) {
      const col = columnsMap[prop] ?? prop

      if (!(col in row)) {
        continue
      }

      const cast = castsMap[prop]

      instance[prop] = cast ? applyCast(row[col], cast) : row[col]
    }

    return instance
  }

  // ── Terminal query methods ─────────────────────────────────────────────────

  async find(id: any): Promise<T | null> {
    return this.query().find(id)
  }

  async get(): Promise<T[]> {
    return this.query().get()
  }

  async first(): Promise<T | null> {
    return this.query().first()
  }

  // ── Chainable query builder methods ───────────────────────────────────────

  where(callback: (group: ConditionGroup) => void): EntityQuery<T>
  where(condition: Condition): EntityQuery<T>
  where(field: Field, value: any): EntityQuery<T>
  where(field: Field, operator: string, value: any): EntityQuery<T>
  where(...args: any[]): EntityQuery<T> {
    return (this.query() as any).where(...args)
  }

  whereIn(field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereIn(field, values)
  }

  whereNotIn(field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereNotIn(field, values)
  }

  whereBetween(field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereBetween(field, range)
  }

  whereNotBetween(field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereNotBetween(field, range)
  }

  whereNull(field: Field): EntityQuery<T> {
    return this.query().whereNull(field)
  }

  whereNotNull(field: Field): EntityQuery<T> {
    return this.query().whereNotNull(field)
  }

  whereLike(field: Field, pattern: string, caseSensitive = false): EntityQuery<T> {
    return this.query().whereLike(field, pattern, caseSensitive)
  }

  whereNotLike(field: Field, pattern: string, caseSensitive = false): EntityQuery<T> {
    return this.query().whereNotLike(field, pattern, caseSensitive)
  }

  whereColumn(field: Field, column: Field): EntityQuery<T>
  whereColumn(field: Field, operator: string, column: Field): EntityQuery<T>
  whereColumn(...args: any[]): EntityQuery<T> {
    return (this.query() as any).whereColumn(...args)
  }

  orderBy(field: Field, direction?: OrderByDirection): EntityQuery<T> {
    return this.query().orderBy(field, direction)
  }

  limit(value: number): EntityQuery<T> {
    return this.query().limit(value)
  }

  offset(value: number): EntityQuery<T> {
    return this.query().offset(value)
  }

  select(...fields: (Field | Field[])[]): EntityQuery<T> {
    return this.query().select(...fields)
  }

  with(relations: string | string[], ...rest: string[]): EntityQuery<T> {
    return this.query().with(relations, ...rest)
  }

  joinRelationship(relationName: string): EntityQuery<T> {
    return this.query().joinRelationship(relationName)
  }

  innerJoinRelationship(relationName: string): EntityQuery<T> {
    return this.query().innerJoinRelationship(relationName)
  }

  leftJoinRelationship(relationName: string): EntityQuery<T> {
    return this.query().leftJoinRelationship(relationName)
  }

  // ── Persistence ────────────────────────────────────────────────────────────

  /**
   * Persists an entity instance to the database.
   * - Primary key set   → UPDATE (auto-generated columns excluded from SET).
   * - Primary key unset → INSERT (auto-generated columns excluded; generated
   *                       PK is written back onto the instance).
   */
  async save(instance: T): Promise<void> {
    const pk = this.primaryKey
    const fieldNames = this.fields
    const autoGeneratedFields = this.autoGeneratedFields
    const castsMap = this.casts
    const columnsMap = this.columnsMap
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const source = this.getSource()
    // Build the column→value row, skipping auto-generated columns
    const row: DataSet = {}
    const cols =
      fieldNames.length > 0
        ? fieldNames
        : Object.keys(instance as any).filter((k) => typeof (instance as any)[k] !== 'function')

    for (const col of cols) {
      if (autoGeneratedFields.includes(col)) {
        continue
      }

      const value = (instance as any)[col]

      if (value === undefined) {
        continue
      }

      const cast = castsMap[col]

      row[columnsMap[col] ?? col] = cast ? applyCastForStorage(value, cast) : value
    }

    if ((instance as any)[pkProp] != null) {
      // UPDATE — exclude PK from SET clause
      const updateRow = { ...row }

      delete updateRow[pk]
      await source
        .table(this.table)
        .where(pk, (instance as any)[pkProp])
        .update(updateRow)
    } else {
      // INSERT — read back the generated ID
      const conn = await source.getConnection()

      try {
        await conn.execute(new InsertQuery().setTable(this.table).setFields(row))

        if (autoGeneratedFields.includes(pkProp)) {
          ;(instance as any)[pkProp] = await conn.lastInsertId()
        }
      } finally {
        await conn.close()
      }
    }
  }

  /**
   * Deletes an entity instance from the database by its primary key.
   * Throws if the primary key is not set on the instance.
   */
  async delete(instance: T): Promise<void> {
    const pk = this.primaryKey
    const columnsMap = this.columnsMap
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const pkValue = (instance as any)[pkProp]

    if (pkValue == null) {
      throw new Error('Cannot delete an entity without a primary key value.')
    }

    await this.getSource().table(this.table).where(pk, pkValue).delete()
  }
}
