import { DataSet } from '../data-set'
import { DataSource } from '../data-source'
import { DB } from '../db'
import { InsertQuery } from '../query'
import { applyCastForStorage } from './decorators/casts'
import { CastType } from './entity'

// ── Entities namespace ────────────────────────────────────────────────────────

export class Entities {
  /**
   * Persists an entity instance to the database.
   * - If the primary key is set → UPDATE (auto-generated columns are excluded from SET).
   * - If the primary key is null/undefined → INSERT (auto-generated columns are excluded;
   *   the generated PK is written back to the instance).
   */
  static async save(entity: object): Promise<void> {
    const cls = entity.constructor as any
    const pk: string = cls.primaryKey
    const tableName: string = cls.table
    const fieldNames: string[] = cls.fields ?? []
    const autoGeneratedFields: string[] = cls.autoGeneratedFields ?? []
    const castsMap: Record<string, CastType> = cls.casts ?? {}
    const source: DataSource = cls.source ?? DB.getActiveSource()
    // Build the row, skipping auto-generated columns (DB manages their values)
    const row: DataSet = {}
    const cols =
      fieldNames.length > 0
        ? fieldNames
        : Object.keys(entity as any).filter((k) => typeof (entity as any)[k] !== 'function')

    for (const col of cols) {
      if (autoGeneratedFields.includes(col)) {
        continue
      }

      const value = (entity as any)[col]

      if (value === undefined) {
        continue
      }

      const cast = castsMap[col]

      row[col] = cast ? applyCastForStorage(value, cast) : value
    }

    if ((entity as any)[pk] != null) {
      // UPDATE — also exclude PK from SET clause
      const updateRow = { ...row }

      delete updateRow[pk]
      await source
        .table(tableName)
        .where(pk, (entity as any)[pk])
        .update(updateRow)
    } else {
      // INSERT — get connection to read back the generated ID
      const conn = await source.getConnection()

      try {
        await conn.execute(new InsertQuery().setTable(tableName).setFields(row))

        if (autoGeneratedFields.includes(pk)) {
          ;(entity as any)[pk] = await conn.lastInsertId()
        }
      } finally {
        await conn.close()
      }
    }
  }

  /**
   * Deletes an entity instance from the database by its primary key.
   * Throws if the primary key is not set.
   */
  static async delete(entity: object): Promise<void> {
    const cls = entity.constructor as any
    const pk: string = cls.primaryKey
    const pkValue = (entity as any)[pk]

    if (pkValue == null) {
      throw new Error('Cannot delete an entity without a primary key value.')
    }

    const source: DataSource = cls.source ?? DB.getActiveSource()

    await source.table(cls.table).where(pk, pkValue).delete()
  }
}
